### PR TITLE
Cu 86775q5wn/allow region list as param

### PR DESCRIPTION
**Pull request by Tay-Sike**
Changes:
- Can now specify regions with --gcp.region_list "regions"
- region_list defaults to ["us-central1","us-east4"]
- Updated README
- Updated main_test

### CODE REVIEW

**Comment by Tay-Sike** [comment]
Task linked: [CU-86775q5wn GQE - add region list to deployment strategy](https://app.clickup.com/t/86775q5wn)

**Review by vborodaykevych — APPROVED** [review]

**Comment by justinb-shipt** [comment]
Don't you have to do something with the `scrape` method in order to limit what regions it's scraping? Or are you making these changes in phases? Or I'm not reading the code correctly which is a strong possibility.

**Comment by justinb-shipt** [comment]
> Don't you have to do something with the `scrape` method in order to limit what regions it's scraping? Or are you making these changes in phases? Or I'm not reading the code correctly which is a strong possibility.

Ah. I see the change to scrape. The diff wasn't giving me a big enough picture and then just look at the file made be lose track of the diff. Still processing. :-)

**Review by justinb-shipt — APPROVED** [review]

**Comment by justinb-shipt** [comment]
Now I see it. Inside scrape you converted your []string into []*compute.Region{}. You could probably save some compute time and skip that step. Have scrape return a []string (region) and then simplify this loop: https://github.com/shipt/gcp-quota-exporter/blob/ad91476331d77b830dc5794d5431c3d9d3547007/main.go#L119. Which is going through []*compute.Region{} and returning the string (Name) you've started with.

**Comment by Tay-Sike** [comment]
My biggest reason for avoiding changing the expected output of `scrape` was because `Collect` uses *compute.RegionList during its for-loop.

But you are right. I could simplify the for-loop because it only utilizes the `.Items` which is []*compute.Region.

I'll try it.

**Review by justinb-shipt — APPROVED** [review]

**Pull request merged**
